export const AUTH_USER = "AUTH_USER";

export const GET_CUSTOMER = "GET_CUSTOMER";
export const CUSTOMER_LOADING = "CUSTOMER_LOADING";
export const CLEAR_CUSTOMER = "CLEAR_CUSTOMER";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORY = "GET_CATEGORY";
export const REMOVE_CATEGORY = "REMOVE_CATEGORY";
export const CATEGORY_LOADING = "CATEGORY_LOADING";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const PRODUCT_LOADING = "PRODUCT_LOADING";

export const GET_CART = "GET_CART";
export const CLEAR_CART = "CLEAR_CART";
export const CART_LOADING = "CART_LOADING";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
